services:
  frontend:
    build:
      context: ./client # Path to the frontend code
      dockerfile: Dockerfile
    ports:
      - "80:80"
    env_file:
      - ./client/.env

  backend:
    build:
      context: ./server/functions/ # Path to the backend code
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - ./server/functions/.env
